---
title: "Assignment2"
author: "jesper fischer ehmsen"
date: "2023-02-23"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cmdstanr)
library(ggtext)
library(posterior)
library(bayesplot)
library(ggdist)
library(brms)
source(here::here("agents.R"))
source(here::here("stan_helpers.R"))

```


## R Markdown


```{r}
#different parameter settings for the game and agents:
#ntrials the number of times the agents play the game
ntrials = 120
#alpha1_l is the learning rate for the first agent (matcher) when losing
alpha1_l = 0
#alpha1_l is the learning rate for the first agent (matcher) when winning
alpha1_w = 0
#alpha2_l is the learning rate for the first agent (non-matcher) when losing
alpha2_l = 0
#alpha1_l is the learning rate for the first agent (non-matcher) when winning
alpha2_w = 0
#bias1 is the bias of the first participant to answer 1. That is if it is 1 then agent 1 will choose 1 on the first trial, if 0.5 he picks at random
bias1 = 0.2
#bias 2 is what bias1 is for agent2
bias2 = 0.2

#the incentive of the first agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive1 = 0
#the incentive of the second agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive2 = 0


#different agents:
#random bias:
#to initialize a random bias agent the learning rates for that agent just have to set to 0 and the bias is will then determine the bias of the agent:

#win stay lose shift (WSLS):
#to initialize a (WSLS) agent the two learning rates for the agent has to be set to 1.

#rescorla wagner(RW) learner with constant learning rate
#to initialize this RW agent the two learning rates for the agent just have to be equal

#rescorla wagner(RW) learner with different learning rate for wins and loses
#to initialize a RW agent the two learning rates for the agent just have to be different:



#make the agents play once (not included)
df = rw_vs_rw(ntrials = ntrials,
         alpha1_l = alpha1_l,
         alpha1_w = alpha1_w,
         alpha2_l = alpha2_l,
         alpha2_w = alpha2_w,
         bias1 = bias1,
         bias2 = bias2,
         incentive1 = incentive1,  
         incentive2 = incentive2
         )

df = data.frame(df)


#lets fit in stan:
filemodel = here::here("assignment2", "stan_models/bias_vs_bias.stan")

mod = cmdstan_model(filemodel)

datap = list(rw1 = df$rw1, rw2 = df$rw2, n = nrow(df), prior = 1)
data = list(rw1 = df$rw1, rw2 = df$rw2, n = nrow(df), prior = 0)


prior <- mod$sample(
  data = datap, 
  seed = 123,
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)

fit <- mod$sample(
  data = data, 
  seed = 123,
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)

prior = as_draws_df(prior$draws())
prior$prior = 1

draws = as_draws_df(fit$draws())
draws$prior = 0

draws2 = rbind(draws,prior)


draws2 %>% pivot_longer(cols = c("theta1_prior","theta2_prior")) %>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value, fill = prior))+geom_density(aes(x = value), alpha = 0.3)+facet_wrap(~name)+scale_fill_manual(values = c("blue","red"))




draws %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value))+facet_wrap(~name)+
  geom_histogram(alpha = 0.8, fill = "darkblue", binwidth = 1, col = "black")+
  geom_histogram(data = prior %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)),aes(x = value),alpha = 0.3, fill = "red", binwidth = 1, col = "black")+xlab(paste("choosing '1' on ",ntrials," trials"))+ylab("posterior density")+
  geom_point(data = df %>% summarize(rw1 = sum(rw1)) %>% mutate(name = "sim_rw1"), aes(x = rw1, y = 0), col = "green",size = 6, shape = 17)+
  geom_point(data = df %>% summarize(rw2 = sum(rw2)) %>% mutate(name = "sim_rw2"), aes(x = rw2, y = 0), col = "green",size = 6, shape = 17)
  


```



```{r}
#priors are normal (0, 2), as the above plot (comes from bias_vs_bias)
#parameter recovery
pr = parameter_recovery_bias_vs_bias(ngames = 20,
                                     trials = 20)

pr$plot
```



```{r}
#sensitivity analysis:
ngamess = 5

sens_mean = sensitivty_bias_vs_bias(ngames = ngamess,
                               trials = 15,
                               mean = seq(-3,3,length.out = ngamess))

sens_mean$plot


sens_sd = sensitivty_bias_vs_bias(ngames = ngamess,
                                  trials = 15,
                                  sd = seq(0.1,1,length.out = ngamess))
sens_sd$plot
```






```{r}
#rw vs Rescorla wagner fit one participant

#different parameter settings for the game and agents:
#ntrials the number of times the agents play the game
ntrials = 120
#alpha1_l is the learning rate for the first agent (matcher) when losing
alpha1_l = 0.8
#alpha1_l is the learning rate for the first agent (matcher) when winning
alpha1_w = 0.8
#alpha2_l is the learning rate for the first agent (non-matcher) when losing
alpha2_l = 0.1
#alpha1_l is the learning rate for the first agent (non-matcher) when winning
alpha2_w = 0.1
#bias1 is the bias of the first participant to answer 1. That is if it is 1 then agent 1 will choose 1 on the first trial, if 0.5 he picks at random
bias1 = 0.5
#bias 2 is what bias1 is for agent2
bias2 = 0.5

#the incentive of the first agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive1 = 0
#the incentive of the second agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive2 = 0


#different agents:
#random bias:
#to initialize a random bias agent the learning rates for that agent just have to set to 0 and the bias is will then determine the bias of the agent:

#win stay lose shift (WSLS):
#to initialize a (WSLS) agent the two learning rates for the agent has to be set to 1.

#rescorla wagner(RW) learner with constant learning rate
#to initialize this RW agent the two learning rates for the agent just have to be equal

#rescorla wagner(RW) learner with different learning rate for wins and loses
#to initialize a RW agent the two learning rates for the agent just have to be different:



#make the agents play once (not included)
df = rw_vs_rw(ntrials = ntrials,
         alpha1_l = alpha1_l,
         alpha1_w = alpha1_w,
         alpha2_l = alpha2_l,
         alpha2_w = alpha2_w,
         bias1 = bias1,
         bias2 = bias2,
         incentive1 = incentive1,  # 0 doesn't care about ,  1 does the oppisite
         incentive2 = incentive2
         )

df = data.frame(df)


#lets fit in stan:

filemodel = here::here("assignment2","stan_models","rw_vs_rw.stan")

mod = cmdstan_model(filemodel)

data = list(rw1 = df$rw1, rw2 = df$rw2, fb_rw1 = df$feedback_rw1, fb_rw2 = df$feedback_rw2, n = nrow(df), prior = 0)
datap = list(rw1 = df$rw1, rw2 = df$rw2, fb_rw1 = df$feedback_rw1, fb_rw2 = df$feedback_rw2, n = nrow(df), prior = 1)

fit <- mod$sample(
  data = data, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)

prior <- mod$sample(
  data = datap, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)





prior = as_draws_df(prior$draws(c("theta1_prior", "theta2_prior","alpha1_prior","alpha2_prior","sim_rw1","sim_rw2")))
prior$prior = 1

draws = as_draws_df(fit$draws(c("theta1_prior", "theta2_prior","alpha1_prior","alpha2_prior","sim_rw1","sim_rw2")))
draws$prior = 0

draws2 = rbind(draws,prior)


draws2 %>% pivot_longer(cols = c("theta1_prior","theta2_prior")) %>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value, fill = prior))+geom_density(aes(x = value), alpha = 0.3)+facet_wrap(~name)+scale_fill_manual(values = c("blue","red"))

draws2 %>% pivot_longer(cols = c("alpha1_prior","alpha2_prior")) %>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value, fill = prior))+geom_density(aes(x = value), alpha = 0.3)+facet_wrap(~name)+scale_fill_manual(values = c("blue","red"))



draws %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value))+facet_wrap(~name)+
  geom_histogram(alpha = 0.8, fill = "darkblue", binwidth = 1, col = "black")+
  geom_histogram(data = prior %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)),aes(x = value),alpha = 0.3, fill = "red", binwidth = 1, col = "black")+xlab(paste("choosing '1' on ",ntrials," trials"))+ylab("posterior density")+
  geom_point(data = df %>% summarize(rw1 = sum(rw1)) %>% mutate(name = "sim_rw1"), aes(x = rw1, y = 0), col = "green",size = 6, shape = 17)+
  geom_point(data = df %>% summarize(rw2 = sum(rw2)) %>% mutate(name = "sim_rw2"), aes(x = rw2, y = 0), col = "green",size = 6, shape = 17)


```


```{r}
#parameter recovery of rescorla wagner vs rescorla wagner



library(ggdist)
#parameter recovery
pr = parameter_recovery_rw_vs_rw(ngames = 5,
                                 trials = 20,
                                 lr1 = 0.3,
                                 lr2 = 0.7)

pr$plot
```



```{r}
#differing learning rates for winning and losing:

#Rw vs RW

#different parameter settings for the game and agents:
#ntrials the number of times the agents play the game
ntrials = 500
#alpha1_l is the learning rate for the first agent (matcher) when losing
alpha1_l = 0.8
#alpha1_l is the learning rate for the first agent (matcher) when winning
alpha1_w = 0.6
#alpha2_l is the learning rate for the first agent (non-matcher) when losing
alpha2_l = 0.6
#alpha1_l is the learning rate for the first agent (non-matcher) when winning
alpha2_w = 0.3
#bias1 is the bias of the first participant to answer 1. That is if it is 1 then agent 1 will choose 1 on the first trial, if 0.5 he picks at random
bias1 = 0.5
#bias 2 is what bias1 is for agent2
bias2 = 0.5

#the incentive of the first agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive1 = 0
#the incentive of the second agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive2 = 0


#different agents:
#random bias:
#to initialize a random bias agent the learning rates for that agent just have to set to 0 and the bias is will then determine the bias of the agent:

#win stay lose shift (WSLS):
#to initialize a (WSLS) agent the two learning rates for the agent has to be set to 1.

#rescorla wagner(RW) learner with constant learning rate
#to initialize this RW agent the two learning rates for the agent just have to be equal

#rescorla wagner(RW) learner with different learning rate for wins and loses
#to initialize a RW agent the two learning rates for the agent just have to be different:



#make the agents play once (not included)
df = rw_vs_rw(ntrials = ntrials,
         alpha1_l = alpha1_l,
         alpha1_w = alpha1_w,
         alpha2_l = alpha2_l,
         alpha2_w = alpha2_w,
         bias1 = bias1,
         bias2 = bias2,
         incentive1 = incentive1,  # 0 doesn't care about ,  1 does the oppisite
         incentive2 = incentive2
         )

df = data.frame(df)

#lets fit in stan:


filemodel = here::here("assignment2","stan_models","rw_win_lose_vs_rw.stan")

mod = cmdstan_model(filemodel)

data = list(rw1 = df$rw1, rw2 = df$rw2, fb_rw1 = df$feedback_rw1, fb_rw2 = df$feedback_rw2, n = nrow(df), prior = 0)
datap = list(rw1 = df$rw1, rw2 = df$rw2, fb_rw1 = df$feedback_rw1, fb_rw2 = df$feedback_rw2, n = nrow(df), prior = 1)


fit <- mod$sample(
  data = data, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)



prior <- mod$sample(
  data = datap, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)







prior = as_draws_df(prior$draws(c("theta1_prior", "theta2_prior","alpha1l_prior","alpha1w_prior","alpha2l_prior","alpha2w_prior","sim_rw1","sim_rw2")))
prior$prior = 1

draws = as_draws_df(fit$draws(c("theta1_prior", "theta2_prior","alpha1l_prior","alpha1w_prior","alpha2l_prior","alpha2w_prior","sim_rw1","sim_rw2")))
draws$prior = 0

draws2 = rbind(draws,prior)


draws2 %>% pivot_longer(cols = c("theta1_prior","theta2_prior")) %>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value, fill = prior))+geom_density(aes(x = value), alpha = 0.3)+facet_wrap(~name)+scale_fill_manual(values = c("blue","red"))

draws2 %>% pivot_longer(cols = c("alpha1l_prior","alpha2l_prior","alpha1w_prior","alpha2w_prior")) %>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value, fill = prior))+
  geom_vline(data = data.frame(name  = c("alpha1l_prior","alpha2l_prior","alpha1w_prior","alpha2w_prior"), vals = c(alpha1_l, alpha2_l,alpha1_w,alpha2_w)),aes(xintercept = vals))+
  geom_density(aes(x = value), alpha = 0.3)+facet_wrap(~name)+scale_fill_manual(values = c("blue","red"))+theme_classic()



draws %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value))+facet_wrap(~name)+
  geom_histogram(alpha = 0.8, fill = "darkblue", binwidth = 1, col = "black")+
  geom_histogram(data = prior %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)),aes(x = value),alpha = 0.3, fill = "red", binwidth = 1, col = "black")+xlab(paste("choosing '1' on ",ntrials," trials"))+ylab("posterior density")+
  geom_point(data = df %>% summarize(rw1 = sum(rw1)) %>% mutate(name = "sim_rw1"), aes(x = rw1, y = 0), col = "green",size = 6, shape = 17)+
  geom_point(data = df %>% summarize(rw2 = sum(rw2)) %>% mutate(name = "sim_rw2"), aes(x = rw2, y = 0), col = "green",size = 6, shape = 17)





```


```{r}
#pr for that:


#prior:
#N(0,1) for all see   hist(inv_logit_scaled(rnorm(10000,0,1)))

pr = parameter_recovery_rw_gen(ngames = 5,
                               start_trials = 75, 
                               end_trials = 125, 
                               lr1_l = 0.3, 
                               lr1_w = 0.8,
                               lr2_l = 0.9,
                               lr2_w = 0.1)
pr$plot

```


```{r}
#sensitivity analysis:


ngamess = 5
sens_mean = sensitivty_recovery_rw_gen(ngames = ngamess,
                               start_trials = 120,
                               end_trials = 122,
                               lr1_l = 0.3, 
                               lr1_w = 0.8,
                               lr2_l = 0.9,
                               lr2_w = 0.1,
                               mean = seq(-3,3,length.out = ngamess))

sens_mean$plot


sens_sd = sensitivty_recovery_rw_gen(ngames = ngamess,
                               start_trials = 120,
                               end_trials = 122,
                               lr1_l = 0.3, 
                               lr1_w = 0.8,
                               lr2_l = 0.9,
                               lr2_w = 0.1,
                               sd = seq(0.1,1,length.out = ngamess))
sens_sd$plot


```





```{r}
#mutilevel modeling of the RW isn't done.

#multilevel_model first see that simulation work
#different parameter settings for the game and agents:
#ntrials the number of times the agents play the game
ntrials = 120
#alpha1_l is the learning rate for the first agent (matcher) when losing
alpha1_l_mu = 0.5
alpha1_l_sd = 0.1

alpha1_w_mu = 0.01
alpha1_w_sd = 0.1


#alpha2_l is the learning rate for the first agent (non-matcher) when losing
alpha2_l_mu = 0.4
alpha2_l_sd = 0.1



alpha2_w_mu = 0.4
alpha2_w_sd = 0.1



#bias1 is the bias of the first participant to answer 1. That is if it is 1 then agent 1 will choose 1 on the first trial, if 0.5 he picks at random
bias1_mu = 0.2
bias1_sd = 0.1

#bias 2 is what bias1 is for agent2
bias2_mu = 0.8
bias2_sd = 0.1


#the incentive of the first agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive1 = 0
#the incentive of the second agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive2 = 0

#make the agents play 100 times and plot it (included)
subjects = 5

agg = rw_vs_rw_hier(subjects = subjects,
         ntrials = ntrials,
         alpha1_l_mu,
         alpha1_l_sd,
         alpha1_w_mu,
         alpha1_w_sd,
         alpha2_l_mu,
         alpha2_l_sd,
         alpha2_w_mu,
         alpha2_w_sd,
         bias1_mu, 
         bias2_mu,
         bias1_sd, 
         bias2_sd,
         incentive1, 
         incentive2)

pairwise = agg$pairlevel
trialevel = agg$triallevel



trialevel$pair = as.factor(trialevel$pair)
trialevel$rw1 = as.factor(trialevel$rw1)

pairwise$pair = as.factor(pairwise$pair)
#plot them:
trialevel %>% mutate(x = rep(1:ntrials,subjects)) %>% 
  pivot_longer(cols = c("expectation1","expectation2")) %>% inner_join(pairwise, by = "pair") %>% 
  ggplot() +
  geom_line(aes(x = x, y = value, col = name))+
  geom_richtext(aes(x = 30, y = 0, label = paste("alpha1 = ", round(alpha1_l,2))), size = 3)+
  geom_richtext(aes(x = 90, y = 0, label = paste("alpha2 = ", round(alpha2_l,2))), size = 3)+
  facet_wrap(~pair)+
  theme_classic()


```

```{r}
#then we fit stan model first simply bias vs bais:


#different parameter settings for the game and agents:
#ntrials the number of times the agents play the game
ntrials = 120
#alpha1_l is the learning rate for the first agent (matcher) when losing
alpha1_l_mu = 0
alpha1_l_sd = 0.01

alpha1_w_mu = 0
alpha1_w_sd = 0.01


#alpha2_l is the learning rate for the first agent (non-matcher) when losing
alpha2_l_mu = 0
alpha2_l_sd = 0.01



alpha2_w_mu = 0
alpha2_w_sd = 0.01

#bias1 is the bias of the first participant to answer 1. That is if it is 1 then agent 1 will choose 1 on the first trial, if 0.5 he picks at random
bias1_mu = 0.2
bias1_sd = 0.05

#bias 2 is what bias1 is for agent2
bias2_mu = 0.9
bias2_sd = 0.05


#the incentive of the first agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive1 = 0
#the incentive of the second agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive2 = 0

#make the agents play 100 times and plot it (included)
subjects = 10



agg = rw_vs_rw_hier(subjects = subjects,
         ntrials = ntrials,
         alpha1_l_mu,
         alpha1_l_sd,
         alpha1_w_mu,
         alpha1_w_sd,
         alpha2_l_mu,
         alpha2_l_sd,
         alpha2_w_mu,
         alpha2_w_sd,
         bias1_mu,
         bias1_sd,
         bias2_mu,
         bias2_sd,
         incentive1, 
         incentive2)

pairwise = agg$pairlevel
trialevel = agg$triallevel


trialevel$pair = as.factor(trialevel$pair)
trialevel$rw1 = as.factor(trialevel$rw1)

pairwise$pair = as.factor(pairwise$pair)
#plot them:
trialevel %>% mutate(x = rep(1:120,subjects)) %>% 
  pivot_longer(cols = c("expectation1","expectation2")) %>% inner_join(pairwise, by = "pair") %>% 
  ggplot() +
  geom_line(aes(x = x, y = value, col = name))+
  geom_richtext(aes(x = 30, y = 0, label = if(alpha1_l[1] != 0){paste("alpha1_l = ", round(alpha1_l,2))}else{paste("bias1 =", round(bias1,2))}), size = 3)+
  geom_richtext(aes(x = 90, y = 0, label = if(alpha2_l[1] != 0){paste("alpha2_l = ", round(alpha2_l,2))}else{paste("bias2 =", round(bias2,2))}), size = 3)+
  facet_wrap(~pair)+
  theme_classic()

data = list(rw1 = as.matrix(agg$rw1), 
            rw2 = as.matrix(agg$rw2), 
            fb_rw1 = as.matrix(agg$rw1_fb), 
            fb_rw2 = as.matrix(agg$rw2_fb), 
            trials = nrow(agg$rw1), 
            subjects = ncol(agg$rw1),
            prior = 0)


datap = list(rw1 = as.matrix(agg$rw1), 
            rw2 = as.matrix(agg$rw2), 
            fb_rw1 = as.matrix(agg$rw1_fb), 
            fb_rw2 = as.matrix(agg$rw2_fb), 
            trials = nrow(agg$rw1), 
            subjects = ncol(agg$rw1),
            prior = 1)

filemodel = here::here("assignment2","stan_models","bias_vs_bias_hier.stan")


mod = cmdstan_model(filemodel)


fit <- mod$sample(
  data = data, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)



prior <- mod$sample(
  data = datap, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)
```




```{r, plot it}

prior = as_draws_df(prior$draws())
prior$prior = 1

draws = as_draws_df(fit$draws())
draws$prior = 0

draws2 = rbind(draws,prior)

#population effects:

draws2 %>% pivot_longer(cols = c("theta1_prior_p","theta2_prior_p")) %>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value, fill = prior))+geom_density(aes(x = value), alpha = 0.3)+facet_wrap(~name)+scale_fill_manual(values = c("blue","red"))+
  geom_vline(data = data.frame(name = c("theta1_prior_p","theta2_prior_p"), vals = c(bias1_mu, bias2_mu)), aes(xintercept = vals))


qq = draws2 %>% filter(prior == 0) %>% select(c(starts_with("theta1_prior["))) %>% pivot_longer(cols = everything()) %>% mutate(agent = as.factor(1)) %>% mutate(name = substr(name, 14, 14))
qq1 = draws2%>% filter(prior == 0) %>% select(c(starts_with("theta2_prior["))) %>% pivot_longer(cols = everything()) %>% mutate(agent = as.factor(2)) %>% mutate(name = substr(name, 14, 14))

qq2 = rbind(qq,qq1)

qq2 %>% ggplot(aes(x = value, fill = agent))+
  geom_density(alpha = 0.3)+facet_wrap(~name)+scale_fill_manual(values = c("blue","red"))+
  theme_classic()+
  geom_vline(data = data.frame(name  = rep(1:subjects,2), vals = c(pairwise$bias1,pairwise$bias2), col = as.factor(c(rep(1,subjects),rep(2,subjects)))),aes(xintercept = vals, col = col))+
  scale_color_manual(values = c("blue","red"))





#draws %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)) %>% ggplot(aes(x = value))+facet_wrap(~name)+
#  geom_histogram(alpha = 0.8, fill = "darkblue", binwidth = 1, col = "black")+
#  geom_histogram(data = prior %>% pivot_longer(cols = c("sim_rw1","sim_rw2"))%>% mutate(prior = as.factor(prior)),aes(x = value),alpha = 0.3, fill = "red", binwidth = 1, col = #"black")+xlab(paste("choosing '1' on ",ntrials," trials"))+ylab("posterior density")+
#  geom_point(data = df %>% summarize(rw1 = sum(rw1)) %>% mutate(name = "sim_rw1"), aes(x = rw1, y = 0), col = "green",size = 6, shape = 17)+
#  geom_point(data = df %>% summarize(rw2 = sum(rw2)) %>% mutate(name = "sim_rw2"), aes(x = rw2, y = 0), col = "green",size = 6, shape = 17)



#mcmc_hist(fit$draws("alpha_1_mu"))
#mcmc_hist(fit$draws("alpha_1_sd"))
#mcmc_hist(fit$draws("alpha_2_mu"))
#mcmc_hist(fit$draws("alpha_2_sd"))



mcmc_hist(fit$draws("theta1_prior_p"))
mcmc_hist(fit$draws("theta2_prior_p"))

#mcmc_hist(fit$draws("alpha_1"))
#mcmc_hist(fit$draws("alpha_2"))


mcmc_hist(fit$draws("theta1_prior"))
mcmc_hist(fit$draws("theta2_prior"))

pairwise
```





```{r, fitting HGF}
#fitting the hgf to a random bias agent

source("/home/jespere/Advanced-cognitive-modeling/assignment2/hgf_agent.R")

bias = c(0.5,rep(c(0.2,0.8),3),0.5)
trials = c(75,rep(c(20,30),3),75)

u = rm_agent(bias,trials)

input = data.frame(kappa = 1.4, theta = 0.5, omega = -4, beta = 5,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)

data = hgf_agentt(u,input)

plothgfdata(data)




```


```{r}
#hgf test
library(tidybayes)
library(cmdstanr)
library(brms)


source(here::here("assignment2", "hgf_agent.R"))

bias = c(0.5,rep(c(0.2,0.8),2),0.5)
trials = c(30,rep(c(15,20),2),30)

u = rm_agent(bias,trials)

input = data.frame(kappa = 1.4, theta = 0.5, omega = -2, beta = 10,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)
data = hgf_agentt(u,input)[-1,]

plothgfdata(data)

filemodel = here::here("assignment2","stan_models","3-level-hgf-no_pu.stan")

mod = cmdstan_model(filemodel)

data1 = list(ntrials = nrow(data), u = data$u, y = data$y)


fit <- mod$sample(
  data = data1,
  chains = 4, 
  parallel_chains = 4,
  refresh = 500,
  adapt_delta = 0.9
  )


posterior = as_draws_df(fit$draws(c("theta","kappa","omega")))
  
mcmc_trace(posterior)

color_scheme_set("blue")


np_cp <- nuts_params(fit)

mcmc_parcoord(posterior, np = np_cp)

mcmc_pairs(posterior, np = np_cp, pars = c("theta","omega","kappa"),
           off_diag_args = list(size = 0.75))


plot_prior_post_update_nopu(fit,
                       real = input,
                       levels = 3)


```

```{r}
#hgf test less trials

source(here::here("assignment2", "hgf_agent.R"))

bias = c(0.5,rep(c(0.1,0.9,0.1,0.9)),0.5)
trials = c(20,rep(c(20,30,20,20)),20)

u = rm_agent(bias,trials)

input = data.frame(kappa = 1.4, theta = 0.3, omega = -2.5,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)
dataq = hgf_agent(u,input)[-1,]

plothgfdata(dataq)

filemodel = here::here("assignment2","stan_models","3-level-hgf-no_pu.stan")

mod = cmdstan_model(filemodel)

data1 = list(ntrials = nrow(dataq), u = dataq$u, y = dataq$y)


fit <- mod$sample(
  data = data1,
  chains = 4, 
  parallel_chains = 4,
  refresh = 500,
  #adapt_delta = 0.85
  )


library(tidybayes)
library(cmdstanr)
library(brms)

posterior = as_draws_df(fit$draws(c("theta","kappa","omega")))
  
mcmc_trace(posterior)

color_scheme_set("blue")


np_cp <- nuts_params(fit)

mcmc_parcoord(posterior, np = np_cp)

mcmc_pairs(posterior, np = np_cp, pars = c("theta","omega","kappa"),
           off_diag_args = list(size = 0.75))


plot_prior_post_update_nopu(fit,
                       real = input,
                       levels = 3)


posterior = as_draws_df(fit$draws(c("p_theta","p_kappa","p_omega")))
  
```



```{r}
#hgf test 2-level
source(here::here("assignment2", "hgf_agent.R"))

bias = c(0.5,rep(c(0.1,0.9,0.1,0.9),1),0.5)
trials = c(100,rep(c(20,30,20,20),1),100)



u = rm_agent(bias,trials)

input = data.frame(kappa = 0, theta = 0, omega = -2.5,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)
dataq = hgf_agent(u,input)[-1,]

plothgfdata(dataq)


setwd("~/Advanced-cognitive-modeling/assignment2")
filemodel = "stan_models/2-level-hgf-no_pu.stan"

mod = cmdstan_model(filemodel)

data1 = list(ntrials = nrow(dataq), u = dataq$u, y = dataq$y, prior = 0)
data1p = list(ntrials = nrow(dataq), u = dataq$u, y = dataq$y, prior = 1)


fit <- mod$sample(
  seed = 111,
  data = data1,
  chains = 4, 
  parallel_chains = 4,
  refresh = 500,
  #adapt_delta = 0.85
  )


fit_prior <- mod$sample(
  seed = 111,
  data = data1p,
  chains = 4, 
  parallel_chains = 4,
  refresh = 500,
  #adapt_delta = 0.85
  )
library(tidybayes)
library(cmdstanr)
library(brms)

posterior = as_draws_df(fit$draws(c("theta","kappa","omega","sim_resp")))
prior = as_draws_df(fit_prior$draws(c("theta","kappa","omega","sim_resp")))

  
mcmc_trace(posterior)

color_scheme_set("blue")



plot_prior_post_update_nopu(fit,
                       real = input,
                       levels = 2)

posterior = as_draws_df(fit$draws())

qq = posterior %>% tidybayes::gather_draws(mu1hat[trials], sa1hat[trials], mu1[trials], sa2[trials], mu2[trials], mu3[trials], sa3[trials],sim_resp_t[trials]) %>% 
  group_by(trials, .variable) %>% 
  summarize(mean = mean(.value)) %>% 
  pivot_wider(names_from = .variable,values_from = mean) %>% filter(trials != nrow(.))

qq$trials = NA
qq$trial = 1:nrow(qq)
qq$y = dataq$y
qq$u = dataq$u

source(here::here("assignment2", "hgf_agent.R"))


plothgfdata(dataq)

plothgfdata(qq[-1,])

```


```{r}
library(tidybayes)
library(cmdstanr)
library(brms)

seed = 123
times = 2
real_omega = seq(-8,-1,0.2)
#hgf parameter recovery
source(here::here("assignment2", "hgf_agent.R"))


setwd("~/Advanced-cognitive-modeling/assignment2")
filemodel = "stan_models/2-level-hgf-no_pu_pr.stan"

mod = cmdstan_model(filemodel)

bias = c(0.8,0.2)
trials = c(10,10)
dff = data.frame(bias = bias, trials = trials)



df5 = purrr::map_df(real_omega, pr_hgf_2level, times = 5)
df5 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df10 = purrr::map_df(real_omega, pr_hgf_2level, times = 10)
df10 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df15 = purrr::map_df(real_omega, pr_hgf_2level, times = 15)
df15 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df20 = purrr::map_df(real_omega, pr_hgf_2level, times = 20)
df20 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df25 = purrr::map_df(real_omega, pr_hgf_2level, times = 25)
df25 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df30 = purrr::map_df(real_omega, pr_hgf_2level, times = 30)
df30 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df35 = purrr::map_df(real_omega, pr_hgf_2level, times = 35)
df35 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df = rbind(df5,df10,df15,df20,df25,df30,df35)
df %>% mutate(trials = as.factor(trials)) %>% ggplot()+geom_pointrange(aes(x = real, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+facet_wrap(~trials)+geom_abline(slope = 1, intercept = 0)



bias = c(0.8,0.2)
trials = c(20,20)
dff = data.frame(bias = bias, trials = trials)
```


```{r}
df2 = purrr::map_df(real_omega, pr_hgf_2level, times = 2)
df2 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df5 = purrr::map_df(real_omega, pr_hgf_2level, times = 5)
df5 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df10 = purrr::map_df(real_omega, pr_hgf_2level, times = 10)
df10 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df15 = purrr::map_df(real_omega, pr_hgf_2level, times = 15)
df15 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df20 = purrr::map_df(real_omega, pr_hgf_2level, times = 20)
df20 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)




df = rbind(df2,df5,df10, df15,df20)
df %>% mutate(trials = as.factor(trials*2)) %>% ggplot()+geom_pointrange(aes(x = real, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+facet_wrap(~trials)+geom_abline(slope = 1, intercept = 0)
```


```{r}
bias = c(0.8,0.2)
trials = c(40,40)
dff = data.frame(bias = bias, trials = trials)


df1 = purrr::map_df(real_omega, pr_hgf_2level, times = 1)
df1 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df2 = purrr::map_df(real_omega, pr_hgf_2level, times = 2)
df2 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df3 = purrr::map_df(real_omega, pr_hgf_2level, times = 3)
df3 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df4 = purrr::map_df(real_omega, pr_hgf_2level, times = 4)
df4 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df5 = purrr::map_df(real_omega, pr_hgf_2level, times = 5)
df5 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df = rbind(df1,df2,df3, df4,df5)
df %>% mutate(trials = as.factor(trials*4)) %>% ggplot()+geom_pointrange(aes(x = real, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+facet_wrap(~trials)+geom_abline(slope = 1, intercept = 0)
```


```{r}
bias = c(0.8,0.2)
trials = c(80,80)
dff = data.frame(bias = bias, trials = trials)


df1 = purrr::map_df(real_omega, pr_hgf_2level, times = 1)
df1 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)

df2 = purrr::map_df(real_omega, pr_hgf_2level, times = 2)
df2 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df3 = purrr::map_df(real_omega, pr_hgf_2level, times = 3)
df3 %>% ggplot()+geom_pointrange(aes(x = real_omega, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+geom_abline(slope = 1, intercept = 0)


df = rbind(df1,df2,df3)
df %>% mutate(trials = as.factor(trials*8)) %>% ggplot()+geom_pointrange(aes(x = real, y = mean, ymin = mean-sd, ymax = mean+sd))+xlab("Simulated values")+ylab("Recovered values")+theme_classic()+facet_wrap(~trials)+geom_abline(slope = 1, intercept = 0)

```

```{r}
#hgf sensitvity

library(tidybayes)
library(cmdstanr)
library(brms)

seed = 123
times = 2
real_omega = seq(-8,-1,0.2)
#hgf parameter recovery
source(here::here("assignment2", "hgf_agent.R"))


setwd("~/Advanced-cognitive-modeling/assignment2")
filemodel = "stan_models/2-level-hgf-no_pu_pr.stan"

mod = cmdstan_model(filemodel)

bias = c(0.8,0.2)
trials = c(40,40)
dff = data.frame(bias = bias, trials = trials)

means = seq(-8,-1, by = 0.5)
sds = seq(0.1,5, by = 0.5)
omega = seq(-5,-1,by = 1)


#hgf parameter recovery
source(here::here("assignment2", "hgf_agent.R"))


df = expand.grid(means = means,sds = sds, omega = omega)

dfq = purrr::pmap_df(df, sensitivity_hgf_2level)

dfq %>% ggplot(aes(x = priormean, y = mean))+geom_point()+facet_grid(real~priorsd, labeller = label_both)+
  ylab("Gathered mean")+xlab("prior mean")+
  geom_hline(aes(yintercept = real))+
  theme_bw()+
    theme(
    plot.title = element_text(size = 18),
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 18),
    legend.text = element_text(size = 18),
    strip.text = element_text(size = 18)
  )

```


