---
title: "shiny HGF-agent"
author: "Jesper Fischer Ehmsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(shiny)
library(ggplot2)
library(shinythemes)
library(shinyWidgets)
library(here)
library(tidyverse)

#input = data.frame(kappa = 1.4, theta = 0.3, omega = -2,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)


source(paste0(here(),"/assignment2/hgf_agent.R"))
    

bias = c(0.1,0.3,0.5,0.9)
trials = c(50,50,50,50)

u = rm_agent(bias,trials)

slider_params1 <- list(
  list("theta", "theta", -10, 10, 0.3, 0.1),
  list("omega", "omega:", -10, 10, -2, 0.1),
  list("kappa", "kappa:", 0, 3, 1.4, 0.1),
  list("Inital_prec2", "Inital_prec2", 0, 20, 4, 0.1),
  list("Inital_mu2", "Inital_mu2", -5, 5, 0, 0.1),
  list("Inital_mu3", "Inital_mu3", -0.5, 0.5, 0, 0.01),
  list("Inital_prec3", "Inital_prec3", 0, 20, 4, 0.1)
)


slider_params2 <- list(
  list("theta1", "theta", -10, 10, 0.3, 0.1),
  list("omega1", "omega:", -10, 10, -2, 0.1),
  list("kappa1", "kappa:", 0, 3, 1.4, 0.1),
  list("nu", "nu:", 0, 3, 1, 0.1),
  list("Inital_prec21", "Inital_prec2", 0, 20, 4, 0.1),
  list("Inital_mu21", "Inital_mu2", -5, 5, 0, 0.1),
  list("Inital_mu31", "Inital_mu3", -0.5, 0.5, 0, 0.01),
  list("Inital_prec31", "Inital_prec3", 0, 20, 4, 0.1)
)


ui <- navbarPage(
  "Hello",
    tabPanel("Page 1",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params1, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
          plotOutput("plot"), height = "2000px")
    )
  ),
  tabPanel("Page 2",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params2, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
          plotOutput("plot1"), height = "2000px")
    )
  )
)



server <- function(input, output) {
 hgf = reactive({

    
    source(paste0(here(),"/assignment2/hgf_agent.R"))
    
    data = hgf_agent(u,input)
        
    q1 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 1, mu2 = NA, sa2 = NA,mu3 = NA,sa3 = NA)
    q2 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 2, mu1hat = NA, sa1hat = NA, mu3 = NA, sa3 = NA, u = NA)
    q3 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 3, mu1hat = NA, sa1hat = NA,mu2 = NA, sa2 = NA, u = NA)
    
    q3 = rbind(q1,q2,q3)
    
    q3$level = as.factor(q3$level)
    
    return(q3)   
 })
 hgf_nu = reactive({

    source(paste0(here(),"/assignment2/hgf_agent.R"))
    
    data = hgf_agent_nu(u,input)
        
    q1 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3,belief) %>% mutate(level = 1, mu2 = NA, sa2 = NA,mu3 = NA,sa3 = NA)
    q2 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 2, mu1hat = NA, sa1hat = NA, mu3 = NA, sa3 = NA, u = NA, belief = NA)
    q3 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 3, mu1hat = NA, sa1hat = NA,mu2 = NA, sa2 = NA, u = NA, belief = NA)
    
    q3 = rbind(q1,q2,q3)
    
    q3$level = as.factor(q3$level)
    
    return(q3)   
 })
 
 
 output$plot <- renderPlot({
    source(paste0(here(),"/assignment2/hgf_agent.R"))

    #u = rm_agent(bias,trials)
    hgf() %>% mutate(level = factor(level, labels = c("Predictions","Expectations","Volatility")),level = factor(level, levels = c("Volatility", "Expectations","Predictions")),lower1 = mu1hat-sa1hat, upper1 = mu1hat+sa1hat, lower2 = mu2-sa2, upper2 = mu2+sa2, lower3 = mu3-sa3, upper3 = mu3+sa3) %>%
    ggplot(aes())+
    geom_line(data = data.frame(level = as.factor("Predictions"), x = 1:length(u), y = rep(bias,trials)),aes(x = 1:length(u), y = rep(bias,trials)))+
    facet_wrap(~level, scales = "free",nrow = 3)+
    geom_line(aes(x = trial, y = mu1hat), col = "#c44e52")+
    geom_point(aes(x = trial, y = u), col = "black")+
    geom_ribbon(aes(x = trial, ymax = upper1, ymin = lower1), fill = "#4c72b0", alpha = 0.5)+
    geom_ribbon(aes(x = trial, ymax = upper2, ymin = lower2), fill  = "#c44e52", alpha = 0.5)+
    #geom_ribbon(aes(x = trial, ymax = upper3, ymin = lower3), fill  = "black", alpha = 0.5)+
    geom_line(aes(x = trial, y = mu2), col = "#c44e52")+
    geom_line(aes(x = trial, y = mu3), col = "black")+
    theme_classic()+
    theme(text = element_text(size=12))+
    ylab(" ")
   
 })
 
 
 output$plot1 <- renderPlot({
    source(paste0(here(),"/assignment2/hgf_agent.R"))

    #u = rm_agent(bias,trials)
    hgf_nu() %>% mutate(level = factor(level, labels = c("Predictions","Expectations","Volatility")),level = factor(level, levels = c("Volatility", "Expectations","Predictions")),lower1 = mu1hat-sa1hat, upper1 = mu1hat+sa1hat, lower2 = mu2-sa2, upper2 = mu2+sa2, lower3 = mu3-sa3, upper3 = mu3+sa3) %>%
    ggplot(aes())+
    geom_line(data = data.frame(level = as.factor("Predictions"), x = 1:length(u), y = rep(bias,trials)),aes(x = 1:length(u), y = rep(bias,trials)))+
    facet_wrap(~level, scales = "free",nrow = 3)+
    geom_line(aes(x = trial, y = mu1hat), col = "#c44e52")+
    geom_line(aes(x = trial, y = belief), col = "black")+
    geom_point(aes(x = trial, y = u), col = "black")+
    geom_ribbon(aes(x = trial, ymax = upper1, ymin = lower1), fill = "#4c72b0", alpha = 0.5)+
    geom_ribbon(aes(x = trial, ymax = upper2, ymin = lower2), fill  = "#c44e52", alpha = 0.5)+
    #geom_ribbon(aes(x = trial, ymax = upper3, ymin = lower3), fill  = "black", alpha = 0.5)+
    geom_line(aes(x = trial, y = mu2), col = "#c44e52")+
    geom_line(aes(x = trial, y = mu3), col = "black")+
    theme_classic()+
    theme(text = element_text(size=12))+
    ylab(" ")
   
 })
  
}
shinyApp(ui = ui, server = server)

```





```{r, fig.height=10,fig.width=10}
source(here::here("assignment2","hgf_agent.R"))

bias = rep(c(0.75,0.5,0.4,0.25))
trials = rep(30,4)

input = data.frame(theta = 0.2, omega = -3, kappa = 0.6, Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0, Inital_prec3 = 4, nu = 0.7)

u = rm_agent(bias, trials)

dataf = data.frame(u = u, ur = rep(bias, each = 30))
df = hgf_agent_nu(dataf, input)
```


```{r, fig.height=10,fig.width=10}
library(patchwork)
library(shiny)
library(ggplot2)
library(shinythemes)
library(shinyWidgets)
library(here)
library(tidyverse)
#input = data.frame(kappa = 1.4, theta = 0.3, omega = -2,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)

source(here("assignment2","hgf_agent.R"))

bias = rep(c(0.75,0.25,0.8,0.5,0.2))
trials = rep(30,5)
u = rm_agent(bias, trials)



slider_params1 <- list(
  list("theta", "theta", -10, 10, 1, 0.1),
  list("omega", "omega:", -10, 10, -4, 0.1),
  list("kappa", "kappa:", 0, 3, 1, 0.1),
  list("nu", "nu:", 0, 10, 0.5, 0.1),
  list("Inital_prec2", "Inital_prec2", 0, 4, 1, 0.1),
  list("Inital_mu2", "Inital_mu2", -5, 5, 0, 0.1),
  list("Inital_mu3", "Inital_mu3", -5, 5, 0, 0.1),
  list("Inital_prec3", "Inital_prec3", 0, 4, 1, 0.1)
)


ui <- fluidPage(
  tabsetPanel(
    tabPanel("Page 1",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params1, function(p) {
            do.call(sliderInput, p)
          }),
          actionButton("new_data", "Generate new data"),
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot", height = "750px"))
      )
    )))
  )
)



server <- function(input, output) {

    
  get_data = eventReactive(input$new_data, {
    source(here("assignment2","hgf_agent.R"))
    bias = bias
    trials = trials
    u = rm_agent(bias, trials)
    ur = rep(bias, each = 30)

    return(data.frame(u,ur))
  })
  
  
 hgf = reactive({
    df = hgf_agent_nu(get_data(), input)
    return(df)   
 })
 
 output$plot <- renderPlot({

    lvl1 = hgf() %>% ggplot(aes())+
     ggtitle("Prediction")+
     #belief on input
    #Actual input
     geom_point(aes(x = trial, y = ifelse(u == 1, 1.1, -0.1)), col = "purple")+
     #underlying probability:
     geom_line(aes(x = 1:length(u), y = rep(bias,trials)), col = "black")+
     #prediction on underlying probability:
     geom_line(aes(x = trial, y = mu1hat), col = "#c44e52")+
     #uncertainty on this belief:
     geom_ribbon(aes(x = trial, ymax = mu1hat+sa1hat, ymin = mu1hat-sa1hat), fill = "#c44e52", alpha = 0.3)+
     geom_line(aes(x = trial, y = belief), col = "green")+
     theme_classic()+
     scale_y_continuous(breaks = seq(0,1,by = 0.1))+
     coord_cartesian(ylim = c(-0.2,1.2))+
     theme(text = element_text(size=12))
 
 
 
    #Second level:
    lvl2 = hgf() %>% ggplot(aes())+ggtitle("Expectations")+
    #belief
    geom_line(aes(x = trial, y = mu2), col = "#4c72b0")+
    #uncertainty:
    geom_ribbon(aes(x = trial, ymax = mu2+sa2, ymin = mu2-sa2), col = "#4c72b0", alpha = 0.3)+
    theme_classic()+
    theme(text = element_text(size=12))
    
    
    #third level:
    
    lvl3 = hgf() %>% ggplot(aes())+ggtitle("Volatility")+
    #belief
    geom_line(aes(x = trial, y = mu3), col = "black")+
    #uncertainty:
    geom_ribbon(aes(x = trial, ymax = mu3+sa3, ymin = mu3-sa3), fill  = "black", alpha = 0.3)+
    theme_classic()+
    theme(text = element_text(size=12))
    

    
    return(lvl3/lvl2/lvl1)
   
 })
 
  
}
shinyApp(ui = ui, server = server)

```


```{r}
source(here("assignment2","hgf_agent.R"))

bias = rep(c(0.75,0.5,0.4,0.25))
trials = rep(30,4)

input = data.frame(theta = 0.2, omega = -3, kappa = 0.6, Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0, Inital_prec3 = 4, nu = 0.7, etaa = 1, etab = 0, alpha = 0.01)

u = rm_agent(bias, trials)


df = hgf_agent_nu_pu(data.frame(u, ur = rep(bias, each = 30)), input)
```



```{r}
library(patchwork)
library(shiny)
library(ggplot2)
library(shinythemes)
library(shinyWidgets)
library(here)
library(tidyverse)
#input = data.frame(kappa = 1.4, theta = 0.3, omega = -2,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)

source(here("assignment2","hgf_agent.R"))

bias = rep(c(0.75,0.25,0.8,0.5,0.2))
trials = rep(30,5)
u = rm_agent(bias, trials)



slider_params1 <- list(
  list("theta", "theta", -10, 10, 1, 0.1),
  list("omega", "omega:", -10, 10, -4, 0.1),
  list("kappa", "kappa:", 0, 3, 1, 0.1),
  list("nu", "nu:", 0, 1, 0.5, 0.1),
  list("alpha", "alpha:", 0, 1, 0.1, 0.01),
  list("etaa", "etaa:", 0, 1, 1, 0.1),
  list("etab", "etab:", 0, 1, 0, 0.1),
  list("Inital_prec2", "Inital_prec2", 0, 4, 1, 0.1),
  list("Inital_mu2", "Inital_mu2", -5, 5, 0, 0.1),
  list("Inital_mu3", "Inital_mu3", -5, 5, 0, 0.1),
  list("Inital_prec3", "Inital_prec3", 0, 4, 1, 0.1)
)


ui <- fluidPage(
  tabsetPanel(
    tabPanel("Page 1",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params1, function(p) {
            do.call(sliderInput, p)
          }),
          actionButton("new_data", "Generate new data"),
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot", height = "750px"))
      )
    )))
  )
)



server <- function(input, output) {

    
  get_data = eventReactive(input$new_data, {
    source(here("assignment2","hgf_agent.R"))
    bias = bias
    trials = trials
    u = rm_agent(bias, trials)
    ur = rep(bias, each = 30)

    return(data.frame(u,ur))
  })
  
  
 hgf = reactive({
    df = hgf_agent_nu_pu(get_data(), input)
    return(df)   
 })
 
 output$plot <- renderPlot({

    lvl1 = hgf() %>% ggplot(aes())+
     ggtitle("Prediction")+
     #belief on input
    #Actual input
     geom_point(aes(x = trial, y = ifelse(u == 1, 1.1, -0.1)), col = "purple")+
     geom_pointrange(aes(x = trial, y = mu1, ymin = mu1-input$alpha, ymax = mu1+input$alpha), col = "yellow")+
     #underlying probability:
     geom_line(aes(x = 1:length(u), y = ur), col = "black")+
     #prediction on underlying probability:
     geom_line(aes(x = trial, y = mu1hat), col = "#c44e52")+
     #uncertainty on this belief:
     geom_ribbon(aes(x = trial, ymax = mu1hat+sa1hat, ymin = mu1hat-sa1hat), fill = "#c44e52", alpha = 0.3)+
     geom_line(aes(x = trial, y = belief), col = "green")+
     theme_classic()+
     scale_y_continuous(breaks = seq(0,1,by = 0.1))+
     coord_cartesian(ylim = c(-0.2,1.2))+
     theme(text = element_text(size=12))
 
 
 
    #Second level:
    lvl2 = hgf() %>% ggplot(aes())+ggtitle("Expectations")+
    #belief
    geom_line(aes(x = trial, y = mu2), col = "#4c72b0")+
    #uncertainty:
    geom_ribbon(aes(x = trial, ymax = mu2+sa2, ymin = mu2-sa2), col = "#4c72b0", alpha = 0.3)+
    theme_classic()+
    theme(text = element_text(size=12))
    
    
    #third level:
    
    lvl3 = hgf() %>% ggplot(aes())+ggtitle("Volatility")+
    #belief
    geom_line(aes(x = trial, y = mu3), col = "black")+
    #uncertainty:
    geom_ribbon(aes(x = trial, ymax = mu3+sa3, ymin = mu3-sa3), fill  = "black", alpha = 0.3)+
    theme_classic()+
    theme(text = element_text(size=12))
    

    
    return(lvl3/lvl2/lvl1)
   
 })
 
  
}
shinyApp(ui = ui, server = server)

```

